version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::677889882207:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-9BXX3I6TLTXY"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::677889882207:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-11FOI8VH3NGJ5"
cloudformation_execution_role = "arn:aws:iam::677889882207:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1I9THMVH3Y2FZ"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-seoauz4gufkm"
image_repository = ""
region = "ap-northeast-1"
